### ISSUE TITLE
Add configuration to enable/disable Solr schema initialization

### ISSUE THREAD

**Issue by ghost** [TAMULib/scholars-discovery#246]
On restart the schema attempts to reinitialize flooding Solr with errors of fields already existing.

Alternative to configuration, it may be ideal to check Solr collection whether schema has been initialized. Also, have to account for dynamic schema modification which will require further planning. 

Another option could be to persist state of collection schema in database.

**Comment by tamu-sad-iii** [comment]
Related to:

- [ ] Prevent duplicate requests to Solr during schematization [#336](https://github.com/TAMULib/scholars-discovery/issues/336)
- [ ] Relocate custom defined fields and create in Solr before schematizing [#346](https://github.com/TAMULib/scholars-discovery/issues/346)
- [ ] Add persistent entity for managing Solr configuration [#367](https://github.com/TAMULib/scholars-discovery/issues/367)
- [ ] Remove Solr configurations from repository and manage schema from the application [#344](https://github.com/TAMULib/scholars-discovery/issues/344)
